#include "Shape.h"
#include "Circle.h"
#include "Rectangle.h"

SUBCLASS_DECLARATION_BEGIN(Shape)
SUBCLASS_DECLARATION(Shape)
SUBCLASS_DECLARATION(Circle)
SUBCLASS_DECLARATION(Rectangle)
SUBCLASS_DECLARATION_END()
